= Docker container: Ethereum testnet miner
Chevdor <chevdor@gmail.com>
v0.1.0, 2016-3-30
:toc:
:source-highlighter: pygments 				// coderay, highlightjs, prettify, and pygments.
:doctype: Article

[Chapter 1]
== Intro
This container is provided by *{author}*. Here is a sample usage:

For the sake of clarity, the following command is split into a few lines. Run it as a single line.

[source,shell,numbered]
```
docker run -it \
   -e THREADS=4 \
   -e ETHERBASE=0x3e37011e4a0ce72bB326CAed68dFD03c077E627A \
   -e EXTRADATA="docker eth miner" \
   -v /Users/will/persistedvol/:/ethdata/datadir \
   ethereum-testnet-miner:latest
```


== Environment Variables

. THREADS
. ETHERBASE
. EXTRADATA

=== THREADS

Optional.
The more the better. The default value is 8.

=== ETHERBASE

Optional but recommended to be set!
This is the address that receives the rewards in Ether for your miner. Don´t forget to change it otherwise you will mine on an address controlled by me. This is not a big issue and you are free to do this to test but you will not be able to use this Ether for your testing.


=== EXTRADATA

Optional.
You may pass extra data to your miner. See https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minersetextra

== Volumes & folder

All the data we should care about is located inside the /ethdata folder in the container. it contains mainly 3 sub folders:

. ipc
. datadir
. ethash

=== /ethdata/ipc
NOTE: The +/ethdata/ipc+ is internal and not exposed as Volume. It contains +geth.ipc+


=== /ethdata/datadir

This is the main data folder. If you do not attach a volume, the whole blockchain will be downloaded from scratch every time. *That will take a lonnng time*.

WARNING: While not attaching this volume is valid, it is highly recommended to map it to a local folder in order to persist your blockchain.

=== /ethdata/ethash

This folder contains one or more big files required to mine. You are free to mount this folder as volume or not.
If you mount it, you will save it. Not mounting it will 'cost' you 5 to 10 minutes until the DAG can be rebuilt.

See also https://github.com/ethereum/wiki/wiki/Ethash-DAG

WARNING: DO NOT MOUNT THIS VOLUME. THERE IS A KNOWN ISSUE AT THE MOMENT, MOUNTING IT WILL CRASH WHEN THE DAG IS CREATED. See https://github.com/ethereum/go-ethereum/issues/1572


