= Docker container: Ethereum testnet miner
Chevdor <chevdor@gmail.com>
v1.5.0, 2016-3-30
:toc:
:source-highlighter: pygments 				// coderay, highlightjs, prettify, and pygments.
:doctype: Article


NOTE: If you read this from Docker Hub, you will find reading from https://github.com/chevdor/ethereum-testnet-miner[GitHub] much more pleasant as +asciidoc+ is better supported there.

[Intro]
== Intro
If you want to test or develop with the Ethereum network, you will probably want to get some Ether (ETH or Ξ) on the testnet and run your testing there.
Mining on the testnet *does not* require a GPU and you can min all fine with a regular CPU.

WARNING: Testnet Ether has no value. It cannot be sold/bought.

This docker container provides an easy way to get started. The only requirement is a working internet connection. You may run the container without any option and it will run fine. However, you probably want to provide at least the 2 following parameters: 

. A volume where the blockchain will be stored. If you don´t, the blockchain will be lost when you destroy the contaniner.
. Your testnet Account/Contract address in order to receive your testnet Ether.

All the other parameters are optional.

This container is provided by *{author}*. Here is a sample usage:

For the sake of clarity, the following command is split into a few lines. Run it as a single line.

[source,shell,numbered]
```
docker run -it \
   -e THREADS=4 \
   -e ETHERBASE=0x3e37011e4a0ce72bB326CAed68dFD03c077E627A \
   -e EXTRADATA="docker eth miner" \
   -v /Users/will/persistedvol/:/ethdata/datadir \
   ethereum-testnet-miner:latest
```


== Environment Variables

. THREADS
. ETHERBASE
. EXTRADATA

=== THREADS

Optional.
The more the better. The default value is 8.

=== ETHERBASE

Optional but recommended to be set!
This is the address that receives the rewards in Ether for your miner. Don´t forget to change it otherwise you will mine on an address controlled by me. This is not a big issue and you are free to do this to test but you will not be able to use this Ether for your testing.


=== EXTRADATA

Optional.
You may pass extra data to your miner. See https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minersetextra



[Volumes and Folders]
== Volumes & folders

All the data we should care about is located inside the +/ethdata+ folder in the container. it contains mainly 3 interesting sub-folders:

. ipc
. datadir
. ethash

=== /ethdata/ipc
NOTE: The +/ethdata/ipc+ is internal and not exposed as Volume. It contains +geth.ipc+


=== /ethdata/datadir

This is the main data folder. If you do not attach a volume, the whole blockchain will be downloaded from scratch every time. *That will take a lonnng time*.

WARNING: While not attaching this volume is valid, it is highly recommended to map it to a local folder in order to persist your blockchain.

=== /ethdata/ethash

This folder contains one or more big files required to mine. You are free to mount this folder as volume or not.
If you mount it, you will save it. Not mounting it will 'cost' you 5 to 10 minutes until the DAG can be rebuilt.

See also https://github.com/ethereum/wiki/wiki/Ethash-DAG

WARNING: DO NOT MOUNT THIS VOLUME. THERE IS A KNOWN ISSUE AT THE MOMENT, MOUNTING IT WILL CRASH WHEN THE DAG IS CREATED. See https://github.com/ethereum/go-ethereum/issues/1572


